lint:
  files_exist:
    - lib/nfcore_external_java_deps.jar
    - conf/modules.config
    - .github/workflows/ci.yml
  files_unchanged:
    - docs/images/nf-core-methylseq_logo_light.png
    - docs/images/nf-core-methylseq_logo_dark.png
    - assets/nf-core-methylseq_logo_light.png
  modules_config: false
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Phil Ewels, Sateesh Peri
  description: Methylation (Bisulfite-Sequencing) Best Practice analysis pipeline, part of the nf-core community.
  force: false
  is_nfcore: true
  name: methylseq
  org: nf-core
  outdir: .
  version: 4.2.0
